Add support for preserving text attributes on enter
ckeditor/ckeditor5-enter pull request #63
Opened 2019-05-28 10:19 UTC by msamsel

### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Feature: Add support for respecting `copyOnEnter` attribute's parameter. Closes #40.

---

### Additional information
*

2019-06-19 11:16 UTC, msamsel commented on tests/entercommand.js
> +					schema.extend( '$text', { allowAttributes: 'foo' } );
When I look back and my code, I start to see some issues :D.
Here probably `bar` attribute should be allowed, but defined without `copyOnEnter` property.

2019-06-19 12:15 UTC, jodator requested changes
Small comments to the code. I'll check the behavior in the meantime as well.

2019-06-19 12:15 UTC, jodator commented on tests/entercommand.js
> +					'unknown attributes are disabled',
```suggestion
					'unknown attributes are not copied',
```

2019-06-19 12:15 UTC, jodator commented on tests/entercommand.js
> +					schema.extend( '$text', { allowAttributes: 'foo' } );
As you wrote: this `bar` should be allowed also.

2019-06-19 12:15 UTC, jodator commented on src/entercommand.js
> +function* getAllowedAttributes( schema, allAttributes ) {
The name is slightly misleading IMO. The name suggest `schema.getAllowedAttributes()` use (well getting allowed attributes in conjunction with schema). But this methods returns attributes that are copied on enter.

I'd go with `getCopyOnEnterAttributes()`.

2019-06-19 12:15 UTC, jodator commented on src/entercommand.js
> +		const filteredAttr = getAllowedAttributes( writer.model.schema, selection.getAttributes() );
AFAIR no `Attr` but `Attributes` (maybe not so inside method as in public API).

Maybe go with  `attributesToCopy` and remove the comment? It should be pretty obious then what happens here so the comment would be not needed. (with conjuction of method rename below).

2019-06-26 14:26 UTC, progmancod commented
Is it possible to set this same behavior to the heading plugin?

2019-07-01 07:39 UTC, Reinmar commented
> Is it possible to set this same behavior to the heading plugin? I mean, copy the element class.

That's a separate piece (subfeature). Here we're copying text attributes. Copying element attributes would be a separate ticket.

2019-07-10 07:46 UTC, msamsel commented
@Mgsy here @jodator already start a review, however, you can also take a look on functionality part. Maybe there exist some not obvious relations and connections, which you might notice.

2019-07-10 13:06 UTC, Mgsy commented
## Steps to reproduce
1. Set the following data: `editor.setData("<p>test</p>")`.
1. Put the caret at the end of "test".
1. Activate bold.
1. Press <kbd>Shift + Enter</kbd>.

## Current result
The attribute is lost.

## GIF
![bug_cke5](https://user-images.githubusercontent.com/20988892/60971356-44353a80-a324-11e9-8942-9a68bd61b518.gif)

2019-07-15 14:52 UTC, jodator requested changes
Small updates to the tests, docs and one API usage.

2019-07-15 14:52 UTC, jodator commented on src/shiftentercommand.js
> +		// transforms: [ [ key1, value1 ], ... ] => [ key1, ... ]
```js
selection.getAttributeKeys()
```
:stuck_out_tongue_winking_eye: 

ps.: the comment is also reduntant IMO - also wrongly written (should start with capital letter and have dot at the end.

2019-07-15 14:52 UTC, jodator commented on src/utils.js
> + * Returns iterator which has filtered attributes read from {@link module:engine/model/selection~Selection#getAttributes selection}.
Should be: `Returns iterable...` as other docs for similar constructs.

Also might just skip `iterable blah blah` and just describe that "Returns attributes that should be preserved on the enter key. Filtering..."

2019-07-15 14:52 UTC, jodator commented on src/utils.js
> + * @param {Iterable.<*>} allAttributes iterator with attributes of current selection.
```suggestion
 * @param {Iterable.<*>} allAttributes Attributes to filter.
```

2019-07-15 14:52 UTC, jodator commented on src/utils.js
> + * @returns {Iterable.<*>} filtered attributes which has `copyOnEnter` property.
```suggestion
 * @returns {Iterable.<*>}
```
AFAICS we don't copy the method description. Most methods do not have a similar description.

2019-07-15 14:52 UTC, jodator commented on tests/utils.js
> +					schema.register( 'foo', { inheritAllFrom: '$block' } );
This line registers a schema object (not an attribute) which is a `block`, similar to `paragraph`.

AFAIR only the `schema.setAttributeProperties()` is required but to have this more elegant you could add:

```js
model.schema.extend( '$text', P allowAttributes: [ 'foo', 'bar', 'baz' ] } );
```

as this behavior is for text attributes only.

2019-07-16 09:56 UTC, jodator commented on src/shiftentercommand.js
> +		// transforms: [ [ key1, value1 ], ... ] => [ key1, ... ]
Also the code :P - fixed.

2019-07-16 10:08 UTC, jodator approved these changes
All is good now. You only missed the `selection.getAttributeKeys()` use instead of custom keys retrieval from `selection.getAttributes()`.

2019-07-16 10:09 UTC, merged

2019-07-16 10:32 UTC, msamsel commented
Yeah, I missed this method somehow 🤦‍♂.